// -- STIMULI --
const maleSingular = [
    "CORAGGIOSO", "ORGOGLIOSO", "OTTIMISTA", "TOLLERANTE", "DETERMINATO", "LEALE", "ELEGANTE", "LOQUACE",
    "IMPREVEDIBILE", "FURBO", "PARSIMONIOSO", "INFLESSIBILE", "DIFFIDENTE", "SFACCIATO", "SEDUCENTE",
    "SEMPLICE", "OBBEDIENTE", "PATRIOTTICO", "DIPLOMATICO", "ROMANTICO"
];

const femaleSingular = [
    "CORAGGIOSA", "ORGOGLIOSA", "OTTIMISTA", "TOLLERANTE", "DETERMINATA", "LEALE", "ELEGANTE", "LOQUACE",
    "IMPREVEDIBILE", "FURBA", "PARSIMONIOSA", "INFLESSIBILE", "DIFFIDENTE", "SFACCIATA", "SEDUCENTE",
    "SEMPLICE", "OBBEDIENTE", "PATRIOTTICA", "DIPLOMATICA", "ROMANTICA"
];


const Plural = [
    "CORAGGIOSI", "ORGOGLIOSI", "OTTIMISTI", "TOLLERANTI", "DETERMINATI", "LEALI", "ELEGANTI", "LOQUACI",
    "IMPREVEDIBILI", "FURBI", "PARSIMONIOSI", "INFLESSIBILI", "DIFFIDENTI", "SFACCIATI", "SEDUCENTI",
    "SEMPLICI", "OBBEDIENTI", "PATRIOTTICI", "DIPLOMATICI", "ROMANTICI"
];



// -- STIMULI --
const maleSingularAttr = [
    "CORAGGIOSO", "ORGOGLIOSO", "OTTIMISTA", "TOLLERANTE", "DETERMINATO", "LEALE", "ELEGANTE", "LOQUACE",
    "IMPREVEDIBILE", "FURBO", "PARSIMONIOSO", "INFLESSIBILE", "DIFFIDENTE", "SFACCIATO", "SEDUCENTE",
    "SEMPLICE", "OBBEDIENTE", "PATRIOTTICO", "DIPLOMATICO", "ROMANTICO",
    "DOMANDA DI CONTROLLO: SELEZIONA +1"

];

const femaleSingularAttr = [
    "CORAGGIOSA", "ORGOGLIOSA", "OTTIMISTA", "TOLLERANTE", "DETERMINATA", "LEALE", "ELEGANTE", "LOQUACE",
    "IMPREVEDIBILE", "FURBA", "PARSIMONIOSA", "INFLESSIBILE", "DIFFIDENTE", "SFACCIATA", "SEDUCENTE",
    "SEMPLICE", "OBBEDIENTE", "PATRIOTTICA", "DIPLOMATICA", "ROMANTICA",
    "DOMANDA DI CONTROLLO: SELEZIONA +1"

];

const Plural80 = [
    "CORAGGIOSI", "ORGOGLIOSI", "OTTIMISTI", "TOLLERANTI", "DETERMINATI", "LEALI", "ELEGANTI", "LOQUACI",
    "IMPREVEDIBILI", "FURBI", "PARSIMONIOSI", "INFLESSIBILI", "DIFFIDENTI", "SFACCIATI", "SEDUCENTI",
    "SEMPLICI", "OBBEDIENTI", "PATRIOTTICI", "DIPLOMATICI", "ROMANTICI",
    "CORAGGIOSI", "ORGOGLIOSI", "OTTIMISTI", "TOLLERANTI", "DETERMINATI", "LEALI", "ELEGANTI", "LOQUACI",
    "IMPREVEDIBILI", "FURBI", "PARSIMONIOSI", "INFLESSIBILI", "DIFFIDENTI", "SFACCIATI", "SEDUCENTI",
    "SEMPLICI", "OBBEDIENTI", "PATRIOTTICI", "DIPLOMATICI", "ROMANTICI",
    "CORAGGIOSI", "ORGOGLIOSI", "OTTIMISTI", "TOLLERANTI", "DETERMINATI", "LEALI", "ELEGANTI", "LOQUACI",
    "IMPREVEDIBILI", "FURBI", "PARSIMONIOSI", "INFLESSIBILI", "DIFFIDENTI", "SFACCIATI", "SEDUCENTI",
    "SEMPLICI", "OBBEDIENTI", "PATRIOTTICI", "DIPLOMATICI", "ROMANTICI",
    "CORAGGIOSI", "ORGOGLIOSI", "OTTIMISTI", "TOLLERANTI", "DETERMINATI", "LEALI", "ELEGANTI", "LOQUACI",
    "IMPREVEDIBILI", "FURBI", "PARSIMONIOSI", "INFLESSIBILI", "DIFFIDENTI", "SFACCIATI", "SEDUCENTI",
    "SEMPLICI", "OBBEDIENTI", "PATRIOTTICI", "DIPLOMATICI", "ROMANTICI"
];

const socid = [
    "Considero importante il gruppo degli Italiani",
    "Mi identifico con il gruppo degli Italiani",
    "Sento forti legami con il gruppo degli Italiani",
    "Sono felice di appartenere al gruppo degli Italiani",
    "Domanda di controllo: seleziona -1",
    "Vedo me stesso appartenente al gruppo degli Italiani",
    "Spesso ho bisogno di giustificarmi per la mia appartenenza al gruppo degli Italiani",
    "Spesso mi vergogno di appartenere al gruppo degli Italiani",
    "Mi sento frenato dalla mia appartenenza al gruppo degli Italiani",
    "Mi sento infastidito dalla mia appartenenza al gruppo degli Italiani",
    "Sono critico sulla mia appartenenza al gruppo degli Italiani"
];